### RigUI Script generated by Bone Manager Addon ###

import bpy

from bpy.utils import register_class, unregister_class

BM_rig_id = "BM_p6vhqa08pwrw"


class BM_PT_rigui_BM_p6vhqa08pwrw(bpy.types.Panel):
	bl_space_type = 'VIEW_3D'
	bl_region_type = 'UI'
	bl_category = 'Item'
	bl_label = "Incineriar"
	bl_idname = "BM_PT_rigui_BM_p6vhqa08pwrw"


	@classmethod
	def poll(self, context):
		try:
			return (context.active_object.data.get("BM_rig_id") == BM_rig_id)
		except (AttributeError, KeyError, TypeError):
			return False

	def draw(self, context):
		arm = context.active_object.data
		bcolls = arm.collections_all
		layout = self.layout
		layout = layout.column()
		row = layout.row(align=True)

		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Switch"], "is_solo", toggle=True, text="Switch")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Switch"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["TWEAK"], "is_solo", toggle=True, text="TWEAK")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "TWEAK"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Root"], "is_solo", toggle=True, text="Root")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Root"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Spine"], "is_solo", toggle=True, text="Spine")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Spine"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)
		row.separator(factor=1.5)
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Cola"], "is_solo", toggle=True, text="Cola")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Cola"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Pelo"], "is_solo", toggle=True, text="Pelo")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Pelo"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Cinturon"], "is_solo", toggle=True, text="Cinturon")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Cinturon"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Orejas"], "is_solo", toggle=True, text="Orejas")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Orejas"
		op.arm_name = context.active_object.name

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Eye"], "is_solo", toggle=True, text="Eye")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Eye"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Shoulders"], "is_solo", toggle=True, text="Shoulders")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Shoulders"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Mouch"], "is_solo", toggle=True, text="Mouch")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Mouch"
		op.arm_name = context.active_object.name

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Eyelids"], "is_solo", toggle=True, text="Eyelids")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Eyelids"
		op.arm_name = context.active_object.name

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Fingers"], "is_solo", toggle=True, text="Fingers")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Fingers"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)
		row.separator(factor=1.5)
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Arm IK Control"], "is_solo", toggle=True, text="Arm IK Control")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Arm IK Control"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["L Arm IK"], "is_solo", toggle=True, text="L Arm IK")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "L Arm IK"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["R Arm IK"], "is_solo", toggle=True, text="R Arm IK")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "R Arm IK"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Arm FK Control"], "is_solo", toggle=True, text="Arm FK Control")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Arm FK Control"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["L Arm FK"], "is_solo", toggle=True, text="L Arm FK")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "L Arm FK"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["R Arm FK"], "is_solo", toggle=True, text="R Arm FK")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "R Arm FK"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)
		row.separator(factor=1.5)
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Leg IK Control"], "is_solo", toggle=True, text="Leg IK Control")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Leg IK Control"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["L Leg IK"], "is_solo", toggle=True, text="L Leg IK")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "L Leg IK"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["R Leg IK"], "is_solo", toggle=True, text="R Leg IK")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "R Leg IK"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Leg FK Control"], "is_solo", toggle=True, text="Leg FK Control")
		picker = slot.row(align=True)
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Leg FK Control"
		op.arm_name = context.active_object.name


class BM_PT_dynamicPanel_BM_p6vhqa08pwrw(bpy.types.Panel):
	bl_category = 'Item'
	bl_label = "Dynamic Panel"
	bl_idname = "BM_PT_dynamicPanelBM_p6vhqa08pwrw"
	bl_space_type = 'VIEW_3D'
	bl_region_type = 'UI'
	bl_options = {'DEFAULT_CLOSED'}

	@classmethod
	def poll(self, context):
		try:
			return (context.active_object.data.get("BM_rig_id") == BM_rig_id)
		except (AttributeError, KeyError, TypeError):
			return False

	def draw(self, context):
		layout = self.layout
		ob = context.active_object
		arm = ob.data
		panels = arm.prop_collection

		header, panel = layout.panel('Head and Neck', default_closed=False)
		header.label(text='Head and Neck')
		if panel:
			box = panel.box()
			row= box.row(align=True)
			row.label(text = 'Neck Rotation')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['neck.001'], '["Neck Rotation"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Head Rotation')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['head.001'], '["Head Rotation"]', text = '', emboss=True, toggle=True, slider=True)

		header, panel = layout.panel('Arm L Switches', default_closed=False)
		header.label(text='Arm L Switches')
		if panel:
			box = panel.box()
			row= box.row(align=True)
			row.label(text = 'Arm L IK -> FK')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Arm L IK -> FK"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Hand L Parents')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Hand L Parents"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Arm L Pivot Parent')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Arm L Pivot Parent"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Shoulder L Rotation')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Shoulder L Rotation"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Arm L FK Rotation')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Arm L FK Rotation"]', text = '', emboss=True, toggle=True, slider=True)

		header, panel = layout.panel('Arm R Switches', default_closed=False)
		header.label(text='Arm R Switches')
		if panel:
			box = panel.box()
			row= box.row(align=True)
			row.label(text = 'Arm R IK -> FK')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Arm R IK -> FK"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Hand R Parents')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Hand R Parents"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Arm R Pivot Parent')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Arm R Pivot Parent"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Shoulder R Rotation')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Shoulder R Rotation"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Arm R FK Rotation')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Arm R FK Rotation"]', text = '', emboss=True, toggle=True, slider=True)

		header, panel = layout.panel('Leg L Switches', default_closed=False)
		header.label(text='Leg L Switches')
		if panel:
			box = panel.box()
			row= box.row(align=True)
			row.label(text = 'Leg L IK -> FK')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Leg L IK -> FK"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Foot L Parents')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Foot L Parents"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Leg L Pivot Parent')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Leg L Pivot Parent"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Leg L Rotation')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['left_leg_01.009'], '["Leg L Rotation"]', text = '', emboss=True, toggle=True, slider=True)

		header, panel = layout.panel('Leg R Switches', default_closed=False)
		header.label(text='Leg R Switches')
		if panel:
			box = panel.box()
			row= box.row(align=True)
			row.label(text = 'Leg R IK -> FK')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Leg R IK -> FK"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Foot R Parents')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Foot R Parents"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Leg R Pivot Parent')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['Switch'], '["Leg R Pivot Parent"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Leg R Rotation')
			row.prop(bpy.data.objects['Incineroar'].pose.bones['right_leg_01.009'], '["Leg R Rotation"]', text = '', emboss=True, toggle=True, slider=True)



class BM_PT_customprops_BM_p6vhqa08pwrw(bpy.types.Panel):
	bl_category = 'Item'
	bl_label = "Rig Properties"
	bl_idname = "BM_PT_customprops_BM_p6vhqa08pwrw"
	bl_space_type = 'VIEW_3D'
	bl_region_type = 'UI'
	bl_options = {'DEFAULT_CLOSED'}

	@classmethod
	def poll(self, context):
		if context.active_object.data.get('BM_rig_id'):
			pose_bones = context.selected_pose_bones
			props = None
			rna_properties = {prop.identifier for prop in bpy.types.PoseBone.bl_rna.properties if prop.is_runtime}
			if context.selected_pose_bones:
				bones = context.selected_pose_bones

			elif context.selected_editable_bones:
				bones = [pose_bones[bone.name] for bone in context.selected_editable_bones]

			elif context.mode == 'OBJECT':
				bones = context.active_object.pose.bones

			else:
				return False
			if bones:
				props = [[prop for prop in bone.items() if prop not in rna_properties] for bone in bones]

			if props and bones:
				return (context.active_object.data.get("BM_rig_id") == BM_rig_id)
			else:
				return False

		else:
			return False

	def draw(self, context):
		layout = self.layout
		pose_bones = context.active_object.pose.bones
		if context.selected_pose_bones:
			bones = context.selected_pose_bones

		elif context.selected_editable_bones:
			bones = [pose_bones[bone.name] for bone in context.selected_editable_bones]

		else:
			bones = context.active_object.pose.bones

		def assign_props(row, val, key):
			row.property = key
			row.data_path = "active_pose_bone"
			try:
				row.value = str(val)
			except:
				pass

		rna_properties = {
			prop.identifier for prop in bpy.types.PoseBone.bl_rna.properties
			if prop.is_runtime
		}

		skip_keys = rna_properties

	# Iterate through selected bones add each prop property of each bone to the panel.
		if context.selected_pose_bones is not None:
			for bone in context.selected_pose_bones:
				for i, in enumerate(sorted(bone.keys())):
					if key not in skip_keys:
						if i == 0:
							box = layout.box()
						val = bone.get(key, "value")
						row = box.row()
						split = row.split(align=True, factor=0.7)
						row = split.row(align=True)
						row.label(text=key, translate=False)
						row = split.row(align=True)
						row.prop(bone, f'["{key}"]', text = "", slider=True)


def get_bones(arm, context, collection, selected):
	if collection:
		bones = arm.collections_all[collection.name].bones
		if selected:
			try:
				bones = [bone for bone in bones if bone.select is True]
			except TypeError:
				return []
	elif selected and not collection:
		try:
			bones = [bone for bone in arm.bones if bone.select is True]
		except TypeError:
			return []
	else:
		bones = arm.bones
	return bones


class BMEX_OT_selectCollection(bpy.types.Operator):
	bl_idname = "bonemanex.collection_select"
	bl_label = ""
	bl_description = "Select all Bones in Collection.\nShift to add to selection. \nAlt to remove from selection"

	bcoll_name : bpy.props.StringProperty(name="Collection name", description="Name of bone collection", default="",)
	arm_name : bpy.props.StringProperty(name="Armature name", description="Name of armature", default="",)

	@classmethod
	def poll(self, context):

		return context.mode == "POSE"

	def __init__(self):
		self.shift = False
		self.alt = False

	def invoke(self, context, event):
		self.shift = event.shift
		self.alt = event.alt

		return self.execute(context)

	def execute(self, context):
		ob = context.active_object
		arm = ob.data
		bcolls = arm.collections_all
		bcoll = arm.collections_all[self.bcoll_name]

		if self.alt:
			bones = get_bones(arm, context, bcoll, True)
			for bone in bones:
				bone.select = False
				bone.select_head = False
				bone.select_tail = False

		else:
			bones = get_bones(arm, context, bcoll, False)
			if not self.shift:
				bpy.ops.pose.select_all(action="DESELECT")

			for bone in bones:
				bone.select = True
				bone.select_head = True
				bone.select_tail = True

		return {"FINISHED"}


classes = (BM_PT_rigui_BM_p6vhqa08pwrw,BMEX_OT_selectCollection, BM_PT_customprops_BM_p6vhqa08pwrw, BM_PT_dynamicPanel_BM_p6vhqa08pwrw, BMEX_OT_selectCollection)

def register():
	for cls in classes:
		try:
			register_class(cls)

		except ValueError:
			pass
def unregister():
	for cls in classes:
		try:
			unregister_class(cls)

		except ValueError:
			pass


	del bpy.types.Scene.BM_p6vhqa08pwrw_presets

if __name__ == "__main__":
	register()